name: Lint

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --show-source --statistics --max-line-length=127 .

