name: Test

on: [pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install package
      run: |
        pip install -e .
        pip install pytest coverage
    - name: Run test suite
      run: coverage run -m pytest -v
    - name: Smoke test
      run: checksec /usr/lib
